[2024-01-27T21:00:23.360+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-27T20:00:00+00:00 [queued]>
[2024-01-27T21:00:23.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-27T20:00:00+00:00 [queued]>
[2024-01-27T21:00:23.391+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-27T21:00:23.391+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-01-27T21:00:23.391+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-27T21:00:23.475+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-01-27 20:00:00+00:00
[2024-01-27T21:00:23.511+0000] {standard_task_runner.py:55} INFO - Started process 1052 to run task
[2024-01-27T21:00:23.530+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-01-27T20:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpta7av77o']
[2024-01-27T21:00:23.531+0000] {standard_task_runner.py:83} INFO - Job 119: Subtask tsk4
[2024-01-27T21:00:23.838+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-01-27T20:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-01-27T21:00:24.066+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-01-27T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-27T20:00:00+00:00
[2024-01-27T21:00:24.071+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-27T21:00:24.072+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-27T21:00:24.093+0000] {subprocess.py:86} INFO - Output:
[2024-01-27T21:00:24.107+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-27T21:00:24.141+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-27T21:00:24.149+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=email_test, task_id=tsk4, execution_date=20240127T200000, start_date=20240127T210023, end_date=20240127T210024
[2024-01-27T21:00:24.186+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 119 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1052)
[2024-01-27T21:00:24.235+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-27T21:00:24.318+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
