[2024-01-24T00:58:23.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk1 manual__2024-01-24T00:58:21.429886+00:00 [queued]>
[2024-01-24T00:58:23.410+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk1 manual__2024-01-24T00:58:21.429886+00:00 [queued]>
[2024-01-24T00:58:23.410+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:58:23.410+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-24T00:58:23.411+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:58:23.441+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-01-24 00:58:21.429886+00:00
[2024-01-24T00:58:23.448+0000] {standard_task_runner.py:55} INFO - Started process 2719 to run task
[2024-01-24T00:58:23.456+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerDag3', 'tsk1', 'manual__2024-01-24T00:58:21.429886+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmpnf1qqjot']
[2024-01-24T00:58:23.459+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask tsk1
[2024-01-24T00:58:23.569+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerDag3.tsk1 manual__2024-01-24T00:58:21.429886+00:00 [running]> on host cd1b9fd02609
[2024-01-24T00:58:23.721+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerDag3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T00:58:21.429886+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-24T00:58:21.429886+00:00
[2024-01-24T00:58:23.722+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T00:58:23.723+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-24T00:58:23.744+0000] {subprocess.py:86} INFO - Output:
[2024-01-24T00:58:23.748+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T00:58:23.768+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T00:58:23.774+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerDag3, task_id=tsk1, execution_date=20240124T005821, start_date=20240124T005823, end_date=20240124T005823
[2024-01-24T00:58:23.803+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 2719)
[2024-01-24T00:58:23.834+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-24T00:58:23.898+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
