[2024-02-03T20:00:11.524+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-03T19:00:00+00:00 [queued]>
[2024-02-03T20:00:11.562+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-03T19:00:00+00:00 [queued]>
[2024-02-03T20:00:11.563+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T20:00:11.563+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-02-03T20:00:11.563+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T20:00:11.609+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-02-03 19:00:00+00:00
[2024-02-03T20:00:11.623+0000] {standard_task_runner.py:55} INFO - Started process 4713 to run task
[2024-02-03T20:00:11.652+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-02-03T19:00:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpkrqqigqr']
[2024-02-03T20:00:11.653+0000] {standard_task_runner.py:83} INFO - Job 603: Subtask tsk4
[2024-02-03T20:00:11.981+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-02-03T19:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-02-03T20:00:12.233+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-02-03T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-03T19:00:00+00:00
[2024-02-03T20:00:12.234+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-02-03T20:00:12.235+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-02-03T20:00:12.265+0000] {subprocess.py:86} INFO - Output:
[2024-02-03T20:00:12.272+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-03T20:00:12.329+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-03T20:00:12.349+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20240203T190000, start_date=20240203T200011, end_date=20240203T200012
[2024-02-03T20:00:12.406+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 603 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 4713)
[2024-02-03T20:00:12.468+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-03T20:00:12.548+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
